[env]
PORT = "9000"
RUST_LOG = "debug"

[config]
skip_core_tasks = true

[tasks.format]
install_crate = "rustfmt"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format", "clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.build_release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.serve]
description = "Start Singalling server"
command = "cargo"
args = ["run"]
dependencies = ["format"]