[package]
name = "world"
version = "0.1.0"
edition = "2021"
authors = ["Russell Wong"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
near-sdk = "4.0.0"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
