[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_derive = "1"
uuid = { version = "1.2.2", features = ["serde", "v4", "v1"] }
