[tasks.format]
install_crate = "rustfmt"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "trunk"
args = ["build"]
dependencies = ["clean"]

[tasks.dev]
command = "trunk"
args = ["serve", "--proxy-backend=ws://localhost:9000/", "--proxy-ws=/ws/"]
dependencies = ["format"]

[tasks.release]
command = "trunk"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]