name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - uses: jetli/trunk-action@v0.1.0
      with:
        # Optional version of trunk to install(eg. 'v0.8.1', 'latest')
    version: 'latest'
    - uses: actions/checkout@v3
    - name: Build App
      working-directory: ./app
      run: cargo make release --verbose
